version: '3.8'

services:
  mariadb:
    image: mariadb:10.9
    container_name: ticket_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticket_service
      MYSQL_USER: ticket_user
      MYSQL_PASSWORD: ticket_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    container_name: ticket_service
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      - GIN_MODE=release
    volumes:
      - ./configs:/app/configs

volumes:
  mariadb_data: